name: d3po
channels:
  - nvidia
  - pytorch
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib=3.8
  - numpy=1.23
  - tqdm=4.65
  - einops=0.7
  - pytorch-cuda=12.4
  - pytorch=2.4
  - torchvision=0.19
  - torchaudio=2.4
  - lightning=2.2
  - openai=1.37
  - wandb=0.16
  - diffusers=0.29.2
  - accelerate=0.34
  - scipy=1.12
  - transformers=4.43.2
  - ml-collections=0.1
  - absl-py=2.1
  - inflect=7
  - pydantic=2.8
  - peft=0.12
  ###### for targetdiff ######
  - vina=1.2.5
  - python-lmdb=1.4
  - pyyaml=6
  - easydict=1.9
  - sentencepiece=0.1.99
  - pdb2pqr=3.6
  - rdkit=2023.09.6
  - openbabel=3.1.1
  ############################
  - pip:
    - jsonargparse[signatures]==4.27.7
    - google-generativeai==0.7.*
    ###### for targetdiff ######
    # git+https://github.com/Valdes-Tresanco-MS/AutoDockTools_py3.git@aee55d50d5bdcfdbcd80220499df8cde2a8f4b2a
    # - meeko==0.1.dev3
    # - pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.4.0+cu124.html
    # - torch_geometric
    ############################